<?php
/**
 * TEC Theme functions and definitions
 */

function tec_theme_setup() {
    // Add theme support
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('custom-logo');
    add_theme_support('automatic-feed-links');
    add_theme_support('html5', array(
        'search-form',
        'comment-form',
        'comment-list',
        'gallery',
        'caption',
    ));

    // Register navigation menus
    register_nav_menus(array(
        'primary' => __('Primary Menu', 'tec-theme'),
        'footer' => __('Footer Menu', 'tec-theme'),
    ));
}
add_action('after_setup_theme', 'tec_theme_setup');

// Enqueue styles and scripts
function tec_theme_scripts() {
    wp_enqueue_style('tec-theme-style', get_stylesheet_uri(), array(), '1.0.0');
    wp_enqueue_script('tec-theme-script', get_template_directory_uri() . '/js/main.js', array(), '1.0.0', true);
}
add_action('wp_enqueue_scripts', 'tec_theme_scripts');

// Add AIRTH meta data to posts
function tec_add_airth_meta() {
    add_post_meta_box(
        'airth_meta_box',
        'AIRTH Generation Details',
        'tec_airth_meta_box_callback',
        'post'
    );
}
add_action('add_meta_boxes', 'tec_add_airth_meta');

function tec_airth_meta_box_callback($post) {
    $airth_generated = get_post_meta($post->ID, '_airth_generated', true);
    $airth_models = get_post_meta($post->ID, '_airth_models', true);
    
    echo '<label><input type="checkbox" name="airth_generated" ' . checked($airth_generated, 'yes', false) . ' /> Generated by AIRTH</label><br>';
    echo '<label>AI Models Used:<br><input type="text" name="airth_models" value="' . esc_attr($airth_models) . '" /></label>';
}

// Save AIRTH meta data
function tec_save_airth_meta($post_id) {
    if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) return;
    if (!current_user_can('edit_post', $post_id)) return;

    $airth_generated = isset($_POST['airth_generated']) ? 'yes' : 'no';
    $airth_models = sanitize_text_field($_POST['airth_models']);

    update_post_meta($post_id, '_airth_generated', $airth_generated);
    update_post_meta($post_id, '_airth_models', $airth_models);
}
add_action('save_post', 'tec_save_airth_meta');