<?php get_header(); ?>

<main class="site-main">
    <?php if (have_posts()) : ?>
        <?php while (have_posts()) : the_post(); ?>
            <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
                <header class="entry-header">
                    <?php the_title('<h1 class="entry-title">', '</h1>'); ?>
                    
                    <?php if (get_post_meta(get_the_ID(), '_airth_generated', true) === 'yes') : ?>
                        <div class="airth-meta">
                            Generated by AIRTH
                            <?php 
                            $models = get_post_meta(get_the_ID(), '_airth_models', true);
                            if ($models) {
                                echo ' using ' . esc_html($models);
                            }
                            ?>
                        </div>
                    <?php endif; ?>
                </header>

                <div class="entry-content<?php echo (get_post_meta(get_the_ID(), '_airth_generated', true) === 'yes') ? ' airth-content' : ''; ?>">
                    <?php the_content(); ?>
                </div>
            </article>
        <?php endwhile; ?>
        
        <?php the_posts_pagination(); ?>
        
    <?php else : ?>
        <p><?php esc_html_e('No posts found.', 'tec-theme'); ?></p>
    <?php endif; ?>
</main>

<?php get_footer(); ?>